import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const proximaNova = localFont({
  src: [
    {
      path: '../../public/font/proxima_nova.ttf',
      style: 'normal',
    },
    {
      path: '../../public/font/proxima_nova_bold.otf',
      style: 'bold',
    },


  ],
})


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (   
    <html lang="en">
      <body  className={proximaNova.className} >{children}</body>
    </html>
  )
}
